export interface MenuItem {
  id: string;
  name: string;
  price: number;
  description: string;
  image: string;
  category: string;
}

export interface Restaurant {
  id: string;
  name: string;
  image: string;
  rating: number;
  description: string;
  deliveryTime: string;
  items: MenuItem[];
}

export interface CartItem {
  id: string;
  restaurantId: string;
  menuItem: MenuItem;
  quantity: number;
  specialInstructions?: string;
}

export interface Order {
  id: string;
  date: string;
  items: CartItem[];
  total: number;
  status: string;
  deliveryAddress: string;
  orderType?: OrderType;
  scheduledDateTime?: string;
  subscriptionData?: SubscriptionData;
  customOrderData?: CustomOrderData;
}

export type OrderType = 'quick' | 'scheduled' | 'regular' | 'custom';

export interface SubscriptionData {
  frequency: 'weekly' | 'monthly';
  startDate: string;
  endDate: string;
  occurrences: number;
}

export interface CustomOrderData {
  photoUri?: string;
  audioUri?: string;
  description?: string;
}

// Mock restaurant data - Real breakfast restaurants only
export const mockRestaurants: Restaurant[] = [

  {
    id: "2",
    name: "Burger Bliss",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
    rating: 4.3,
    description: "Juicy burgers and crispy fries",
    deliveryTime: "20-30 min",
    items: [
      {
        id: "2-1",
        name: "Classic Cheeseburger",
        price: 199,
        description: "Beef patty with cheddar and lettuce",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop",
        category: "Burgers",
      },
      {
        id: "2-2",
        name: "Bacon Burger",
        price: 249,
        description: "Beef patty with crispy bacon and cheese",
        image: "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=400&h=300&fit=crop",
        category: "Burgers",
      },
      {
        id: "2-3",
        name: "Double Patty Burger",
        price: 299,
        description: "Two beef patties with cheese and toppings",
        image: "https://images.unsplash.com/photo-1550547990-25967502a51c?w=400&h=300&fit=crop",
        category: "Burgers",
      },
      {
        id: "2-4",
        name: "Crispy Fries",
        price: 99,
        description: "Golden crispy fries with salt",
        image: "https://images.unsplash.com/photo-1584054505923-5ac028344000?w=400&h=300&fit=crop",
        category: "Sides",
      },
      {
        id: "2-5",
        name: "Onion Rings",
        price: 129,
        description: "Crispy battered onion rings",
        image: "https://images.unsplash.com/photo-1639024471694-d6ace3bac628?w=400&h=300&fit=crop",
        category: "Sides",
      },
    ],
  },
  {
    id: "3",
    name: "Sushi Sensation",
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=300&fit=crop",
    rating: 4.7,
    description: "Fresh sushi and Japanese delicacies",
    deliveryTime: "35-45 min",
    items: [
      {
        id: "3-1",
        name: "California Roll",
        price: 249,
        description: "Crab, avocado, and cucumber",
        image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=300&fit=crop",
        category: "Sushi",
      },
      {
        id: "3-2",
        name: "Salmon Nigiri",
        price: 199,
        description: "Fresh salmon on rice (6 pieces)",
        image: "https://images.unsplash.com/photo-1614707267537-b85faf00021b?w=400&h=300&fit=crop",
        category: "Sushi",
      },
      {
        id: "3-3",
        name: "Spicy Tuna Roll",
        price: 229,
        description: "Spicy tuna with cucumber and avocado",
        image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=300&fit=crop",
        category: "Sushi",
      },
      {
        id: "3-4",
        name: "Edamame",
        price: 129,
        description: "Steamed soybeans with salt",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Appetizers",
      },
      {
        id: "3-5",
        name: "Miso Soup",
        price: 99,
        description: "Traditional miso soup with tofu",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
        category: "Soups",
      },
    ],
  },
  {
    id: "4",
    name: "Taco Fiesta",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
    rating: 4.4,
    description: "Authentic Mexican tacos and burritos",
    deliveryTime: "25-35 min",
    items: [
      {
        id: "4-1",
        name: "Chicken Tacos",
        price: 179,
        description: "Three soft tacos with grilled chicken",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
        category: "Tacos",
      },
      {
        id: "4-2",
        name: "Beef Burrito",
        price: 219,
        description: "Flour tortilla with seasoned beef and beans",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
        category: "Burritos",
      },
      {
        id: "4-3",
        name: "Vegetable Quesadilla",
        price: 189,
        description: "Grilled tortilla with cheese and veggies",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
        category: "Quesadillas",
      },
      {
        id: "4-4",
        name: "Churros",
        price: 129,
        description: "Fried dough with cinnamon sugar",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Desserts",
      },
      {
        id: "4-5",
        name: "Guacamole & Chips",
        price: 149,
        description: "Fresh guacamole with tortilla chips",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Appetizers",
      },
    ],
  },
  {
    id: "5",
    name: "Biryani House",
    image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
    rating: 4.6,
    description: "Authentic Indian biryani and curries",
    deliveryTime: "30-40 min",
    items: [
      {
        id: "5-1",
        name: "Chicken Biryani",
        price: 249,
        description: "Fragrant rice with tender chicken",
        image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
        category: "Biryani",
      },
      {
        id: "5-2",
        name: "Mutton Biryani",
        price: 299,
        description: "Aromatic rice with tender mutton",
        image: "https://images.unsplash.com/photo-1585937421612-70a19fb6930b?w=400&h=300&fit=crop",
        category: "Biryani",
      },
      {
        id: "5-3",
        name: "Butter Chicken",
        price: 229,
        description: "Creamy tomato sauce with chicken",
        image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
        category: "Curries",
      },
      {
        id: "5-4",
        name: "Paneer Tikka",
        price: 189,
        description: "Grilled cottage cheese with spices",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Appetizers",
      },
      {
        id: "5-5",
        name: "Naan Bread",
        price: 79,
        description: "Traditional Indian flatbread",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Breads",
      },
    ],
  },
  {
    id: "6",
    name: "Poke Bowl Co",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
    rating: 4.5,
    description: "Fresh poke bowls and salads",
    deliveryTime: "15-25 min",
    items: [
      {
        id: "6-1",
        name: "Salmon Poke Bowl",
        price: 279,
        description: "Fresh salmon with rice and toppings",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
        category: "Poke Bowls",
      },
      {
        id: "6-2",
        name: "Tuna Poke Bowl",
        price: 269,
        description: "Fresh tuna with rice and vegetables",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
        category: "Poke Bowls",
      },
      {
        id: "6-3",
        name: "Veggie Bowl",
        price: 189,
        description: "Mixed vegetables with quinoa",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop",
        category: "Bowls",
      },
      {
        id: "6-4",
        name: "Green Salad",
        price: 149,
        description: "Fresh mixed greens with dressing",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
        category: "Salads",
      },
      {
        id: "6-5",
        name: "Mango Smoothie",
        price: 129,
        description: "Fresh mango smoothie",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Beverages",
      },
    ],
  },
  {
    id: "7",
    name: "Pasta Perfetto",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
    rating: 4.4,
    description: "Premium pasta and Italian dishes",
    deliveryTime: "28-38 min",
    items: [
      {
        id: "7-1",
        name: "Lasagna",
        price: 289,
        description: "Layers of pasta with meat sauce",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
        category: "Pasta",
      },
      {
        id: "7-2",
        name: "Penne Arrabbiata",
        price: 249,
        description: "Spicy tomato sauce with penne",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
        category: "Pasta",
      },
      {
        id: "7-3",
        name: "Ravioli",
        price: 269,
        description: "Cheese-filled ravioli with sauce",
        image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=300&fit=crop",
        category: "Pasta",
      },
      {
        id: "7-4",
        name: "Garlic Bread",
        price: 99,
        description: "Toasted bread with garlic butter",
        image: "https://images.unsplash.com/photo-1599599810694-b5ac4dd64b73?w=400&h=300&fit=crop",
        category: "Sides",
      },
      {
        id: "7-5",
        name: "Tiramisu",
        price: 159,
        description: "Classic Italian dessert",
        image: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=400&h=300&fit=crop",
        category: "Desserts",
      },
    ],
  },
  {
    id: "8",
    name: "Chicken Express",
    image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=300&fit=crop",
    rating: 4.2,
    description: "Crispy fried chicken and wings",
    deliveryTime: "20-30 min",
    items: [
      {
        id: "8-1",
        name: "Fried Chicken Bucket",
        price: 399,
        description: "8 pieces of crispy fried chicken",
        image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=300&fit=crop",
        category: "Chicken",
      },
      {
        id: "8-2",
        name: "Chicken Wings",
        price: 249,
        description: "6 pieces of spicy wings",
        image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=300&fit=crop",
        category: "Chicken",
      },
      {
        id: "8-3",
        name: "Chicken Tenders",
        price: 199,
        description: "4 crispy chicken tenders",
        image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=300&fit=crop",
        category: "Chicken",
      },
      {
        id: "8-4",
        name: "Coleslaw",
        price: 79,
        description: "Fresh coleslaw salad",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
        category: "Sides",
      },
      {
        id: "8-5",
        name: "Soft Drink",
        price: 49,
        description: "250ml soft drink",
        image: "https://images.unsplash.com/photo-1554866585-acbb2f46b34c?w=400&h=300&fit=crop",
        category: "Beverages",
      },
    ],
  },
  {
    id: "udupi",
    name: "Udupi Hotel",
    image: "https://live.staticflickr.com/65535/50012104981_b3f3cb9018_b.jpg",
    rating: 4.5,
    description: "Traditional South Indian breakfast",
    deliveryTime: "20-30 min",
    items: [
      {
        id: "udupi-1",
        name: "Masala Dosa",
        price: 70,
        description: "ಮಸಾಲೆ ದೋಸೆ",
        image: "https://live.staticflickr.com/65535/50012104981_b3f3cb9018_b.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-2",
        name: "Set Dosa (3)",
        price: 70,
        description: "ಸೆಟ್ ದೋಸೆ (3)",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRpOuOoaxHgLzKwiJ8oooMAO40_k0HFMJJSg&s",
        category: "Dosa",
      },
      {
        id: "udupi-3",
        name: "Plain Dosa",
        price: 60,
        description: "ಪ್ಲೇನ್ ದೋಸೆ",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/dosa-recipe.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-4",
        name: "Onion Dosa",
        price: 75,
        description: "ಈರುಳ್ಳಿ ದೋಸೆ",
        image: "https://momsdosapalace.net/wp-content/uploads/2024/07/rava-onion-dosa-117.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-5",
        name: "Open Butter Masala Dosa",
        price: 80,
        description: "ಓಪನ್ ಬಟರ್ ಮಸಾಲೆ ದೋಸೆ",
        image: "https://i.redd.it/0l8jcv80b25d1.jpeg",
        category: "Dosa",
      },
      {
        id: "udupi-6",
        name: "Rava Dosa",
        price: 80,
        description: "ರವಾ ದೋಸೆ",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/05/rava-dosa-recipe.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-7",
        name: "Rava Masala Dosa",
        price: 85,
        description: "ರವಾ ಮಸಾಲೆ ದೋಸೆ",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/05/rava-dosa-recipe.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-8",
        name: "Rava Onion Dosa",
        price: 90,
        description: "ರವಾ ಈರುಳ್ಳಿ ದೋಸೆ",
        image: "https://purohitcafe.com/wp-content/uploads/2024/06/veg-dosa.webp",
        category: "Dosa",
      },
      {
        id: "udupi-9",
        name: "Rava Onion Masala",
        price: 100,
        description: "ರವಾ ಈರುಳ್ಳಿ ಮಸಾಲೆ ದೋಸೆ",
        image: "https://purohitcafe.com/wp-content/uploads/2024/06/veg-dosa.webp",
        category: "Dosa",
      },
      {
        id: "udupi-10",
        name: "Butter Masala Dosa",
        price: 80,
        description: "ಬಟರ್ ಮಸಾಲೆ ದೋಸೆ",
        image: "https://media-cdn.tripadvisor.com/media/photo-s/2b/7c/87/a0/butter-masala-dosa.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-11",
        name: "Butter Plain Dosa",
        price: 70,
        description: "ಬಟರ್ ಪ್ಲೇನ್ ದೋಸೆ",
        image: "https://media-cdn.tripadvisor.com/media/photo-s/2b/7c/87/a0/butter-masala-dosa.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-12",
        name: "Ghee Masala Dosa",
        price: 80,
        description: "ತುಪ್ಪ ಮಸಾಲೆ ದೋಸೆ",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4WFoHm3ASn2oKjkQMeZ_nQ7D93NQkHWz5HA&s",
        category: "Dosa",
      },
      {
        id: "udupi-13",
        name: "Paper Masala Dosa",
        price: 100,
        description: "ಪೇಪರ್ ಮಸಾಲೆ ದೋಸೆ",
        image: "https://www.nandanmsd.com/wp-content/uploads/2020/08/unnamed.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-14",
        name: "Paper Plain Dosa",
        price: 90,
        description: "ಪೇಪರ್ ಪ್ಲೇನ್ ದೋಸೆ",
        image: "https://thumbs.dreamstime.com/b/south-indian-delight-south-indian-delight-paper-masala-dosa-sambhar-coconut-chutney-presented-fresh-banana-leaf-399425299.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-15",
        name: "Neer Dosa",
        price: 80,
        description: "ನೀರ್ ದೋಸೆ",
        image: "https://www.awesomecuisine.com/wp-content/uploads/2013/08/Neer-Dosa.jpg",
        category: "Dosa",
      },
      {
        id: "udupi-16",
        name: "Set Masala Dosa (2)",
        price: 70,
        description: "ಸೆಟ್ ಮಸಾಲೆ ದೋಸೆ (2)",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUXZMBLmghtc-WMToPBnejEcjCnaGY00svaQ&s",
        category: "Dosa",
      },
      {
        id: "udupi-17",
        name: "Benne Dosa (2)",
        price: 70,
        description: "ಬೆಣ್ಣೆ ದೋಸೆ (2)",
        image: "https://www.neehees.com/wp-content/uploads/2025/12/Butter-Meets-Batter_-Why-Benne-Dosa-Tastes-So-Different-from-Regular-Dosa.webp",
        category: "Dosa",
      },
      {
        id: "udupi-18",
        name: "Idly (1)",
        price: 20,
        description: "ಇಡ್ಲಿ (1)",
        image: "https://pbs.twimg.com/media/F0zcHoAagAA_QjL.jpg",
        category: "Idly & Vada",
      },
      {
        id: "udupi-19",
        name: "Idly (2)",
        price: 35,
        description: "ಇಡ್ಲಿ (2)",
        image: "https://cdn.uengage.io/uploads/64296/image-7276-1758286110.jpg",
        category: "Idly & Vada",
      },
      {
        id: "udupi-20",
        name: "Vada (1)",
        price: 30,
        description: "ವಡ (1)",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Medu_Vadas.JPG/1200px-Medu_Vadas.JPG",
        category: "Idly & Vada",
      },
      {
        id: "udupi-21",
        name: "Idly (1) Vada (1)",
        price: 50,
        description: "ಇಡ್ಲಿ (1) ವಡ (1)",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Idli_and_Medu_Vada.JPG/2560px-Idli_and_Medu_Vada.JPG",
        category: "Idly & Vada",
      },
      {
        id: "udupi-22",
        name: "Idly (2) Vada (1)",
        price: 65,
        description: "ಇಡ್ಲಿ (2) ವಡ (1)",
        image: "https://flashplus.in/restaurants/wp-content/uploads/sites/5/2024/04/Idli-Vada-Plate.webp",
        category: "Idly & Vada",
      },
      {
        id: "udupi-23",
        name: "Rava Idly",
        price: 40,
        description: "ರವಾ ಇಡ್ಲಿ",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiNic7QYnJiuaIIDGQ_pS8osrFXn1YZgb5Zg&s",
        category: "Idly & Vada",
      },
      {
        id: "udupi-24",
        name: "Rice Bath / Veg Pulav",
        price: 50,
        description: "ರೈಸ್ ಬಾತ್ / ವೆಜ್ ಪಲಾವ್",
        image: "https://c.ndtvimg.com/2023-01/bcdjpkg_pulao_625x300_31_January_23.jpg",
        category: "Rice Items",
      },
      {
        id: "udupi-25",
        name: "Bisibelebath / Pongal",
        price: 50,
        description: "ಬಿಸಿಬೇಳೆಬಾತ್ / ಪೊಂಗಲ್",
        image: "https://www.indianveggiedelight.com/wp-content/uploads/2020/06/bisibelebath.jpg",
        category: "Rice Items",
      },
      {
        id: "udupi-26",
        name: "Shavige Bath",
        price: 50,
        description: "ಶಾವಿಗೆ ಬಾತ್",
        image: "https://as2.ftcdn.net/jpg/05/29/09/75/1000_F_529097521_tK4dfWh255jKUNdlzcFdylgwMahUFbKq.jpg",
        category: "Rice Items",
      },
      {
        id: "udupi-27",
        name: "Kesari Bath",
        price: 35,
        description: "ಕೇಸರಿ ಬಾತ್",
        image: "https://shrikripa.in/wp-content/uploads/2021/11/DSC_0744-1024x683.jpg",
        category: "Sweet Items",
      },
      {
        id: "udupi-28",
        name: "Kara Bath",
        price: 35,
        description: "ಖಾರ ಬಾತ್",
        image: "https://ravitiffinservice.wordpress.com/wp-content/uploads/2019/09/img201908161053451336713087275706865.jpg",
        category: "Rice Items",
      },
      {
        id: "udupi-29",
        name: "Chow Chow Bath",
        price: 70,
        description: "ಚೌ ಚೌ ಬಾತ್",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBH4vBhBptIwTebhVhM6K-wSSnZB7QSi01KQ&s",
        category: "Rice Items",
      },
      {
        id: "udupi-30",
        name: "Pakoda / Bajji",
        price: 40,
        description: "ಪಕೋಡ / ಬಜ್ಜಿ",
        image: "https://www.whiskaffair.com/wp-content/uploads/2020/07/Onion-Pakoda-2-3.jpg",
        category: "Snacks",
      },
      {
        id: "udupi-31",
        name: "Poori Sagu (3)",
        price: 70,
        description: "ಪೂರಿ ಸಾಗು (3)",
        image: "https://i.ytimg.com/vi/5rJcBfOGPrg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBC5Uz_KNhwXxqyrdsGV7ifLiDtQQ",
        category: "Snacks",
      },
      {
        id: "udupi-32",
        name: "Bonda Soup",
        price: 40,
        description: "ಬೋಂಡಾ ಸೂಪ್",
        image: "https://thephotowali.wordpress.com/wp-content/uploads/2018/08/fb_img_1535548661720-011390930691.jpeg",
        category: "Snacks",
      },
      {
        id: "udupi-33",
        name: "Curd Rice",
        price: 50,
        description: "ಮೊಸರನ್ನ",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/curd-rice-thayir-sadam.jpg",
        category: "Rice Items",
      },
      {
        id: "udupi-34",
        name: "Buns (1)",
        price: 30,
        description: "ಬನ್ಸ್ (1)",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Sesame_seed_hamburger_buns.jpg/1200px-Sesame_seed_hamburger_buns.jpg",
        category: "Snacks",
      },
      {
        id: "udupi-35",
        name: "Curd Vada",
        price: 40,
        description: "ಮೊಸರು ವಡ",
        image: "https://static.toiimg.com/photo/55432577.cms",
        category: "Idly & Vada",
      },
    ],
  },
  {
    id: "shree",
    name: "Shree Hotel",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400&h=300&fit=crop",
    rating: 4.4,
    description: "Delicious breakfast options",
    deliveryTime: "25-35 min",
    items: [
      {
        id: "shree-1",
        name: "Idli",
        price: 20,
        description: "Soft steamed rice cakes",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/01/pongal-ven-pongal.webp",
        category: "Idly & Vada",
      },
      {
        id: "shree-2",
        name: "Vada",
        price: 24,
        description: "Crispy lentil donuts",
        image: "https://palatesdesire.com/wp-content/uploads/2022/03/chana-dal-masala-vada@palates-desire.jpg",
        category: "Idly & Vada",
      },
      {
        id: "shree-3",
        name: "Khali Dosa",
        price: 20,
        description: "Plain crispy dosa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvhPONQp4iTjoGCEk73yNn417UYFvMEoCqvA&s",
        category: "Dosa",
      },
      {
        id: "shree-4",
        name: "Special Khali Dosa",
        price: 30,
        description: "Special plain dosa",
        image: "https://foodofinterest.com/wp-content/uploads/2016/06/DSC_0169_00168.jpg",
        category: "Dosa",
      },
      {
        id: "shree-5",
        name: "Masala Dosa",
        price: 60,
        description: "Crispy dosa with potato masala",
        image: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
        category: "Dosa",
      },
      {
        id: "shree-6",
        name: "Set Masala Dosa",
        price: 60,
        description: "Set of masala dosas",
        image: "https://static.toiimg.com/thumb/54289752.cms?imgsize=495844&width=800&height=800",
        category: "Dosa",
      },
      {
        id: "shree-7",
        name: "Butter Set Masala",
        price: 70,
        description: "Butter set dosa with masala",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1H8Mu-pfh7Rb3kFFqkAs9BGl3KstjAFkb4A&s",
        category: "Dosa",
      },
      {
        id: "shree-8",
        name: "Butter Masala",
        price: 70,
        description: "Butter dosa with masala filling",
        image: "https://www.cookwithkushi.com/wp-content/uploads/2021/12/IMG_5800f.jpg",
        category: "Dosa",
      },
      {
        id: "shree-9",
        name: "Plane Dosa",
        price: 50,
        description: "Plain dosa",
        image: "https://i.pinimg.com/564x/99/7c/e5/997ce5bce8cb202a9239976da11f5920.jpg",
        category: "Dosa",
      },
      {
        id: "shree-10",
        name: "Butter Plane Dosa",
        price: 60,
        description: "Plain dosa with butter",
        image: "https://i.ytimg.com/vi/HWcA_4SeMo0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDk9sRcwgn0BPmE9WX10HUVIQgwWg",
        category: "Dosa",
      },
      {
        id: "shree-11",
        name: "Rice Bath",
        price: 40,
        description: "Aromatic spiced rice",
        image: "https://www.chitrasfoodbook.com/wp-content/uploads/2023/10/Karnataka20rice20bath-5.jpg",
        category: "Rice Items",
      },
      {
        id: "shree-12",
        name: "Bisi Bele Bath",
        price: 40,
        description: "Spicy lentil rice",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Bisi_Bele_Bath_%28Bisibelebath%29.JPG/1200px-Bisi_Bele_Bath_%28Bisibelebath%29.JPG",
        category: "Rice Items",
      },
      {
        id: "shree-13",
        name: "Pongal",
        price: 40,
        description: "Savory rice and lentil dish",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpRtkDZEmdKBoIw0MSefoRo_U0KHF-36EnQg&s",
        category: "Rice Items",
      },
      {
        id: "shree-14",
        name: "Poori",
        price: 55,
        description: "Fried puffed bread",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrgEo7ID_gcMgSDS2ELpo_KzCCW47-tnRzrA&s",
        category: "Snacks",
      },
      {
        id: "shree-15",
        name: "Kesari Bath",
        price: 25,
        description: "Sweet semolina dessert",
        image: "https://img-global.cpcdn.com/recipes/717bfd824b56bd23/1200x630cq80/photo.jpg",
        category: "Sweet Items",
      },
      {
        id: "shree-16",
        name: "Khara Bath",
        price: 25,
        description: "Spicy semolina upma",
        image: "https://www.yummyoyummy.com/wp-content/uploads/2017/12/DSC_0487.jpg",
        category: "Rice Items",
      },
      {
        id: "shree-17",
        name: "Chow Chow Bath",
        price: 45,
        description: "Sweet and spicy combo",
        image: "https://i0.wp.com/www.chitrasfoodbook.com/wp-content/uploads/2018/07/chow-chow-bath-1.jpg?ssl=1",
        category: "Rice Items",
      },
      {
        id: "shree-18",
        name: "Shavige Bath",
        price: 50,
        description: "Spiced vermicelli",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh_R6MH6SSCpiePRKeY4ZaWlVuphh8JD99ow&s",
        category: "Rice Items",
      },
      {
        id: "shree-19",
        name: "Rava Idli",
        price: 30,
        description: "Semolina steamed cakes",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoOQoVDRmDY1CcubEQ2AMq4MMHMbEs1kwizg&s",
        category: "Idly & Vada",
      },
      {
        id: "shree-20",
        name: "Kuruth Curd",
        price: 60,
        description: "Thick curd variety",
        image: "https://images.hindustantimes.com/img/2022/02/17/1600x900/curd_thumb_1645083411793_1645083426228.jpg",
        category: "Snacks",
      },
      {
        id: "shree-21",
        name: "Bajji",
        price: 24,
        description: "Crispy fried fritters",
        image: "https://i0.wp.com/www.chitrasfoodbook.com/wp-content/uploads/2015/03/andhra-mirapakaya-bajji-recipe.jpg?w=1200&ssl=1",
        category: "Snacks",
      },
      {
        id: "shree-22",
        name: "Set Dosa",
        price: 30,
        description: "Soft spongy dosas (set)",
        image: "https://vanitascorner.com/wp-content/uploads/2021/10/Set-Dosa.jpg",
        category: "Dosa",
      },
      {
        id: "shree-23",
        name: "Bonda Soup",
        price: 30,
        description: "Potato dumpling in soup",
        image: "https://thephotowali.wordpress.com/wp-content/uploads/2018/08/fb_img_1535548661720-011390930691.jpeg",
        category: "Snacks",
      },
      {
        id: "shree-24",
        name: "Curd Vada",
        price: 45,
        description: "Vada soaked in yogurt",
        image: "https://static.toiimg.com/photo/55432577.cms",
        category: "Idly & Vada",
      },
      {
        id: "shree-25",
        name: "Tomato Dosa",
        price: 50,
        description: "Dosa with tomato topping",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmqDo5KghROhg5gBSTkodqy-bSDD8xR0CdKw&s",
        category: "Dosa",
      },
      {
        id: "shree-26",
        name: "Butter Set Masala Single",
        price: 35,
        description: "Single butter set masala",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/masala-dosa.jpg",
        category: "Dosa",
      },
      {
        id: "shree-27",
        name: "Single Set Masala",
        price: 30,
        description: "Single set masala dosa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTG4WjfodA0iKltVc2zhJZa1f3yMvIyFw5Kg&s",
        category: "Dosa",
      },
      {
        id: "shree-28",
        name: "Sweet",
        price: 25,
        description: "Traditional sweet variety",
        image: "https://s7ap1.scene7.com/is/image/itcportalprod/The%20sweet%20diversity%20of%20india_Hero%20banner",
        category: "Sweet Items",
      },
    ],
  },
  {
    id: "shree-tiffanis",
    name: "Shree Tiffanis Hotel",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&h=300&fit=crop",
    rating: 4.3,
    description: "Fresh tiffin items",
    deliveryTime: "20-30 min",
    items: [
      {
        id: "tiffanis-1",
        name: "Masale Dosa",
        price: 55,
        description: "Crispy dosa with masala filling",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP6PGZ9yKVUvYztjMrqDXk3hHXTHcZksGVIQ&s",
        category: "Dosa",
      },
      {
        id: "tiffanis-2",
        name: "Plain Dosa",
        price: 50,
        description: "Classic plain dosa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTG4WjfodA0iKltVc2zhJZa1f3yMvIyFw5Kg&s",
        category: "Dosa",
      },
      {
        id: "tiffanis-3",
        name: "Butter Dosa",
        price: 65,
        description: "Butter masala dosa",
        image: "https://img-global.cpcdn.com/recipes/69b099a6b0ef3318/680x781cq80/davanagere-benne-dose-or-butter-dosa-recipe-main-photo.jpg",
        category: "Dosa",
      },
      {
        id: "tiffanis-4",
        name: "Set Masale Dosa",
        price: 55,
        description: "Set of masala dosas",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBD6tNtaWVFy0bF8L6PwNikJyD3zLdectBjQ&s",
        category: "Dosa",
      },
      {
        id: "tiffanis-5",
        name: "Onion Dosa",
        price: 60,
        description: "Dosa topped with onions",
        image: "https://i.redd.it/oap6s514eisb1.jpg",
        category: "Dosa",
      },
      {
        id: "tiffanis-6",
        name: "Normal Dosa",
        price: 40,
        description: "Simple dosa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlzhEBQvOVuRRV4naXHg1SgfMrXvcIQbjz9Q&s",
        category: "Dosa",
      },
      {
        id: "tiffanis-7",
        name: "Bisibele Bath",
        price: 40,
        description: "Spicy lentil rice",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzzXTy9RF_G5rietx33J_z9xTKYgGCA9UEpw&s",
        category: "Rice Items",
      },
      {
        id: "tiffanis-8",
        name: "Khara Bath",
        price: 30,
        description: "Spicy semolina upma",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/khara-bath-recipe.jpg",
        category: "Rice Items",
      },
      {
        id: "tiffanis-9",
        name: "Rava Idli (1)",
        price: 30,
        description: "Single rava idli",
        image: "https://www.sharmispassions.com/wp-content/uploads/2012/07/RavaIdli6-e1668478539613.jpg",
        category: "Idly & Vada",
      },
      {
        id: "tiffanis-10",
        name: "Akki Idli (2)",
        price: 40,
        description: "Two rice idlis",
        image: "https://i0.wp.com/delishbite.in/wp-content/uploads/2023/01/blog_1-2.jpg?resize=1000%2C1250&ssl=1",
        category: "Idly & Vada",
      },
      {
        id: "tiffanis-11",
        name: "Uddina Vada",
        price: 20,
        description: "Crispy lentil vada",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Medu_Vadas.JPG/1200px-Medu_Vadas.JPG",
        category: "Idly & Vada",
      },
      {
        id: "tiffanis-12",
        name: "Bonda Soup",
        price: 30,
        description: "Potato dumpling soup",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuqo-w6ZcMhZ6u_6qwTjwpobQ1R50CciQmkA&s",
        category: "Snacks",
      },
      {
        id: "tiffanis-13",
        name: "Bajji (1 Plate)",
        price: 30,
        description: "Plate of crispy bajjis",
        image: "https://images.slurrp.com/prod/recipe_images/transcribe/snacks/Bajji.webp",
        category: "Snacks",
      },
    ],
  },
  {
    id: "shree-kanteshwara",
    name: "Shree Kanteshwara Hotel",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&h=300&fit=crop",
    rating: 4.6,
    description: "Quality breakfast meals",
    deliveryTime: "25-30 min",
    items: [
      {
        id: "kanteshwara-1",
        name: "Idli",
        price: 20,
        description: "Soft steamed rice cakes",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/01/pongal-ven-pongal.webp",
        category: "Idly & Vada",
      },
      {
        id: "kanteshwara-2",
        name: "Vada",
        price: 24,
        description: "Crispy lentil donuts",
        image: "https://palatesdesire.com/wp-content/uploads/2022/03/chana-dal-masala-vada@palates-desire.jpg",
        category: "Idly & Vada",
      },
      {
        id: "kanteshwara-3",
        name: "Khali Dosa",
        price: 20,
        description: "Plain crispy dosa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvhPONQp4iTjoGCEk73yNn417UYFvMEoCqvA&s",
        category: "Dosa",
      },
      {
        id: "kanteshwara-4",
        name: "Special Khali Dosa",
        price: 30,
        description: "Special plain dosa",
        image: "https://foodofinterest.com/wp-content/uploads/2016/06/DSC_0169_00168.jpg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-5",
        name: "Masala Dosa",
        price: 60,
        description: "Crispy dosa with potato masala",
        image: "https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-6",
        name: "Set Masala Dosa",
        price: 60,
        description: "Set of masala dosas",
        image: "https://static.toiimg.com/thumb/54289752.cms?imgsize=495844&width=800&height=800",
        category: "Dosa",
      },
      {
        id: "kanteshwara-7",
        name: "Butter Set Masala",
        price: 70,
        description: "Butter set dosa with masala",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1H8Mu-pfh7Rb3kFFqkAs9BGl3KstjAFkb4A&s",
        category: "Dosa",
      },
      {
        id: "kanteshwara-8",
        name: "Butter Masala",
        price: 70,
        description: "Butter dosa with masala",
        image: "https://www.cookwithkushi.com/wp-content/uploads/2021/12/IMG_5800f.jpg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-9",
        name: "Plane Dosa",
        price: 50,
        description: "Plain dosa",
        image: "https://i.pinimg.com/564x/99/7c/e5/997ce5bce8cb202a9239976da11f5920.jpg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-10",
        name: "Butter Plane Dosa",
        price: 60,
        description: "Plain dosa with butter",
        image: "https://i.ytimg.com/vi/HWcA_4SeMo0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDk9sRcwgn0BPmE9WX10HUVIQgwWg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-11",
        name: "Rice Bath",
        price: 40,
        description: "Aromatic spiced rice",
        image: "https://www.chitrasfoodbook.com/wp-content/uploads/2023/10/Karnataka20rice20bath-5.jpg",
        category: "Rice Items",
      },
      {
        id: "kanteshwara-12",
        name: "Bisi Bele Bath",
        price: 40,
        description: "Spicy lentil rice",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Bisi_Bele_Bath_%28Bisibelebath%29.JPG/1200px-Bisi_Bele_Bath_%28Bisibelebath%29.JPG",
        category: "Rice Items",
      },
      {
        id: "kanteshwara-13",
        name: "Pongal",
        price: 40,
        description: "Savory rice and lentil dish",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpRtkDZEmdKBoIw0MSefoRo_U0KHF-36EnQg&s",
        category: "Rice Items",
      },
      {
        id: "kanteshwara-14",
        name: "Poori",
        price: 55,
        description: "Fried puffed bread",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrgEo7ID_gcMgSDS2ELpo_KzCCW47-tnRzrA&s",
        category: "Snacks",
      },
      {
        id: "kanteshwara-15",
        name: "Kesari Bath",
        price: 25,
        description: "Sweet semolina dessert",
        image: "https://img-global.cpcdn.com/recipes/717bfd824b56bd23/1200x630cq80/photo.jpg",
        category: "Sweet Items",
      },
      {
        id: "kanteshwara-16",
        name: "Khara Bath",
        price: 25,
        description: "Spicy semolina upma",
        image: "https://www.yummyoyummy.com/wp-content/uploads/2017/12/DSC_0487.jpg",
        category: "Rice Items",
      },
      {
        id: "kanteshwara-17",
        name: "Chow Chow Bath",
        price: 45,
        description: "Sweet and spicy combo",
        image: "https://i0.wp.com/www.chitrasfoodbook.com/wp-content/uploads/2018/07/chow-chow-bath-1.jpg?ssl=1",
        category: "Rice Items",
      },
      {
        id: "kanteshwara-18",
        name: "Shavige Bath",
        price: 50,
        description: "Spiced vermicelli",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSh_R6MH6SSCpiePRKeY4ZaWlVuphh8JD99ow&s",
        category: "Rice Items",
      },
      {
        id: "kanteshwara-19",
        name: "Rava Idli",
        price: 30,
        description: "Semolina steamed cakes",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoOQoVDRmDY1CcubEQ2AMq4MMHMbEs1kwizg&s",
        category: "Idly & Vada",
      },
      {
        id: "kanteshwara-20",
        name: "Kuruth Curd",
        price: 60,
        description: "Thick curd variety",
        image: "https://images.hindustantimes.com/img/2022/02/17/1600x900/curd_thumb_1645083411793_1645083426228.jpg",
        category: "Snacks",
      },
      {
        id: "kanteshwara-21",
        name: "Bajji",
        price: 24,
        description: "Crispy fried fritters",
        image: "https://i0.wp.com/www.chitrasfoodbook.com/wp-content/uploads/2015/03/andhra-mirapakaya-bajji-recipe.jpg?w=1200&ssl=1",
        category: "Snacks",
      },
      {
        id: "kanteshwara-22",
        name: "Set Dosa",
        price: 30,
        description: "Soft spongy dosas (set)",
        image: "https://vanitascorner.com/wp-content/uploads/2021/10/Set-Dosa.jpg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-23",
        name: "Bonda Soup",
        price: 30,
        description: "Potato dumpling in soup",
        image: "https://thephotowali.wordpress.com/wp-content/uploads/2018/08/fb_img_1535548661720-011390930691.jpeg",
        category: "Snacks",
      },
      {
        id: "kanteshwara-24",
        name: "Curd Vada",
        price: 45,
        description: "Vada soaked in yogurt",
        image: "https://static.toiimg.com/photo/55432577.cms",
        category: "Idly & Vada",
      },
      {
        id: "kanteshwara-25",
        name: "Tomato Dosa",
        price: 50,
        description: "Dosa with tomato topping",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmqDo5KghROhg5gBSTkodqy-bSDD8xR0CdKw&s",
        category: "Dosa",
      },
      {
        id: "kanteshwara-26",
        name: "Butter Set Masala Single",
        price: 35,
        description: "Single butter set masala",
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/masala-dosa.jpg",
        category: "Dosa",
      },
      {
        id: "kanteshwara-27",
        name: "Single Set Masala",
        price: 30,
        description: "Single set masala dosa",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTG4WjfodA0iKltVc2zhJZa1f3yMvIyFw5Kg&s",
        category: "Dosa",
      },
    ],
  },
];
